In [357]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [358]:
# df = pd.read_csv("https://raw.githubusercontent.com/danishmeh/Scripts_of_Machine_Learning_Book/main/Chapter_3/Data.csv")

In [359]:
# df.to_csv("data.csv")

In [360]:
df = pd.read_csv("data.csv")
df.head()

Unnamed: 0  Country   Age   Salary Purchased
0           0   France  44.0  72000.0        No
1           1    Spain  27.0  48000.0       Yes
2           2  Germany  30.0  54000.0        No
3           3    Spain  38.0  61000.0        No
4           4  Germany  40.0      NaN       Yes

In [361]:
df.drop(columns=["Unnamed: 0"],inplace=True,axis=1)

In [362]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [363]:
df.shape

(10, 4)

# Extracting the indepedent and dependent variable

In [364]:
X = df.iloc[:,:-1].values
# : first for all rows
# : for all Column
#  -1 for except last column select 

In [365]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [366]:
# agr -1 select karye gye to main data mei last column select ho ga,: first for rows and -1 for last columns
# agr -2 for second last columns  salary wala select ho ho ga
# agr -3 for 3rd column age
# agr -4 for 4 columns ountry wala select ho ga
y = df.iloc[:,-1].values

# Removing Nan Values

In [367]:
# finding missing data using sklearn
# remove nan values with nan function
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Label Encoder

In [368]:
# # country variable convert into 
# from sklearn.preprocessing import LabelEncoder
# label_encoder_X = LabelEncoder()
# X[:,0] = label_encoder_X.fit_transform(X[:,0])
# print(X)

# Encoding categorical data
# Encoding the Independent Variable

In [369]:
# ab data 0,1,2 mei hai jis ki waja sea model in values ko appas mei link karye ga
# to is k liye Dummy vaiable istamal ho ga

In [370]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## y label transformation

In [371]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

## Splitting the dataset into the Training set and Test set

In [372]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

# X_train 

In [373]:
print(X_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


# X_test

In [374]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 50.0 83000.0]]


# y_train,y_test

In [375]:
print(y_train)
print(y_test)

[1 1 1 0 1 0 0 1]
[0 0]


# standard scaler

In [376]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:]= sc.fit_transform(X_train[:,3:])
print(X_train)

[[0.0 1.0 0.0 0.2630675731713538 0.1238147854838185]
 [1.0 0.0 0.0 -0.25350147960148617 0.4617563176278856]
 [0.0 0.0 1.0 -1.9753983221776195 -1.5309334063940294]
 [0.0 0.0 1.0 0.05261351463427101 -1.1114197802841526]
 [1.0 0.0 0.0 1.6405850472322605 1.7202971959575162]
 [0.0 0.0 1.0 -0.08131179534387283 -0.16751412153692966]
 [1.0 0.0 0.0 0.9518263102018072 0.9861483502652316]
 [1.0 0.0 0.0 -0.5978808481167128 -0.48214934111933727]]


In [379]:
X_test[:,3:] =sc.transform(X_test[:,3:])

In [380]:
print(X_test)

[[0.0 1.0 0.0 -4.1 -4.724206896551724]
 [0.0 1.0 0.0 -3.9 -4.724068965517241]]
